version: '2'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
    - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://hipster_hair:secret_password@postgres/
      - SECRET_TOKEN=somethingsosecretevenyoucantguessit
    networks:
      - hipster_hair_network
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - hipster_hair_network
    environment:
      - POSTGRES_USER=hipster_hair
      - POSTGRES_PASSWORD=secret_password
networks:
  hipster_hair_network:
    driver: bridge
volumes:
  postgres:

